### ISSUE TITLE
ST3 Broken, NimLime.add_module

### ISSUE THREAD

**Issue by s-trooper** [Varriount/NimLime#28]
Hi, "NimLime.add_module" don't work in ST3 in no "module":

Running python -u "C:\Dev\Local\env\app-win\sublime-text-3\Data\Packages\NimLime\AutoComplete.py"
reloading plugin NimLime.AutoComplete
Traceback (most recent call last):
  File "C:\Dev\Local\env\app-win\sublime-text-3\sublime_plugin.py", line 72, in reload_plugin
    m = imp.reload(m)
  File "./imp.py", line 276, in reload
  File "C:\Dev\Local\env\app-win\sublime-text-3\sublime_plugin.py", line 678, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "C:\Dev\Local\env\app-win\sublime-text-3\Data\Packages\NimLime\AutoComplete.py", line 10, in <module>
    NimLime.add_module(__name__)
AttributeError: 'module' object has no attribute 'add_module'

I am not sure but could be problem with "mutual top-level imports" ...

**Comment by s-trooper** [comment]
Thank you for instant fix i appreciate that very :). Now i have no errors and that is fine for itself, i have syntax and build script. But neither check nor autocomplete work/nothing happens ...

**Comment by Varriount** [comment]
Is the Nim exe in your PATH environment variable?
