### ISSUE TITLE
Trackback Error misc.py

### ISSUE THREAD

**Issue by pyloor** [Varriount/NimLime#42]
Hi,
i use ST3 and a fresh installed version of your package. This is the error message i receive in the console:
```pyhon
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/utils/misc.py", line 103, in loop_status_generator
  File "NimCheck in /home/user/.config/sublime-text-3/Installed Packages/NimLime.sublime-package", line 115, in run
  File "/home/user/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/utils/misc.py", line 316, in write_to_output
  File "/home/user/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/utils/misc.py", line 132, in get_output_view
  File "/home/user/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/utils/misc.py", line 182, in show_view
TypeError: Can't convert 'NoneType' object to str implicitly
```
How can I fix this?

Thanks in advance,
pyloor

**Comment by Varriount** [comment]
Are you running any specific command or action when you get this error?

**Comment by Varriount** [comment]
Ok, I think I've fixed this. Please give any feedback about the console output mode - I'm debating on whether to keep, as it's a bit complicated to maintain.
