### ISSUE TITLE
Error when I tried to "Install Nimble Package" from the command palette in Sublime 3

### ISSUE THREAD

**Issue by WildYorkies** [Varriount/NimLime#72]
Here is the log from the install error:

```
2016-05-18: 13:31:02
[Stack frames]
[Thread 1600]
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\NimLime-master\nimlime_core\utils\misc.py", line 130, in _loop_status_generator
    flag.flag()
  File "<string>", line 14, in error_handler
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\NimLime-master\nimlime_core\utils\error_handler.py", line 134, in _handle_error
    traceback.print_stack(stack_frame, file=logfile)
Main Traceback (most recent call last):
  File "<string>", line 11, in error_handler
  File "C:\Users\myName\AppData\Roaming\Sublime Text 3\Packages\NimLime-master\nimlime_core\commands\nimble.py", line 230, in run
    if process.poll() != 0:
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by Varriount** [comment]
Sorry for the delay, I've been busy with other life things.

Has this caused any problems since installation? I don't get this error when installing NimLime normally - are you using the most stable version pushed to package control, or are you using the latest code from the repository?

**Comment by timotheecour** [comment]
@WildYorkies @Varriount also got this error
on OSX
sublime 3.1.1 build 3176 (latest)
using regular install
