### ISSUE TITLE
Suggest not works

### ISSUE THREAD

**Issue by Jipok** [Varriount/NimLime#88]
On F12 i just get "Unable to find XXX".
![_2017-09-17_19-30-54](https://user-images.githubusercontent.com/25588359/30521799-c1a13b3a-9bde-11e7-9448-3a1bf8ebae15.png)
On ctrl+shift+p "Nim: Goto Defenition":
```python
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "~/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/utils/idetools.py", line 122, in run
    process = self.check_process(None)
  File ~/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/utils/idetools.py", line 112, in check_process
    result = subprocess.Popen(**self.process_args)
  File "./python3.3/subprocess.py", line 756, in __init__
ValueError: creationflags is only supported on Windows platforms
```
If i delete 83th line in idetools.py:
```python
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "~/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/utils/idetools.py", line 189, in run
    debug_print("Finished request, ", len(entries), " entries found.")
TypeError: object of type 'NoneType' has no len()
```

OS: ManjaroLinux 17.0.5
Sublime Text: Build 3142
Nim: stable 0.17.2 (2017-09-07) [Linux: amd64]

**Comment by Jipok** [comment]
Also at each start in the logs:
```
Error loading scope:source.asm: Unable to find syntax file for scope source.asm in Packages/NimLime/Syntaxes/Nim.tmLanguage
Error loading scope:source.glsl: Unable to find syntax file for scope source.glsl in Packages/NimLime/Syntaxes/Nim.tmLanguage
```

**Comment by Jipok** [comment]
I got another version. Still not working.
Sublime Text 2: Version 2.0.2, Build 2221
```
Reloading plugin ~/.config/sublime-text-2/Packages/NimLime/NimLime.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./NimLime.py", line 11, in <module>
    execfile('__init__.py')
  File "__init__.py", line 22, in <module>
    from nimlime_core.commands import *
  File "./nimlime_core/commands/__init__.py", line 63, in <module>
    load_submodules()
  File "./nimlime_core/commands/__init__.py", line 42, in load_submodules
    loader.find_module(module_name).load_module(module_name)
  File ".\pkgutil.py", line 238, in load_module
  File "~/.config/sublime-text-2/Packages/NimLime/nimlime_core/commands/hotkeys.py", line 24, in <module>
    gen_sync_settings("doccontinue.enabled", True)
  File "~/.config/sublime-text-2/Packages/NimLime/nimlime_core/commands/hotkeys.py", line 21, in gen_sync_settings
    settings.run_on_load_and_change(key, sync_settings)  
  File "./nimlime_core/settings.py", line 68, in run_on_load_and_change
    run_on_load(callback)
  File "./nimlime_core/settings.py", line 46, in run_on_load
    callback()
  File "~/.config/sublime-text-2/Packages/NimLime/nimlime_core/commands/hotkeys.py", line 17, in sync_settings
    v = sublime.active_window().active_view()
AttributeError: 'NoneType' object has no attribute 'active_view'
```
GNU/Linux is not supported?

**Comment by Varriount** [comment]
What version of Sublime Text are you running?

**Comment by Jipok** [comment]
> Sublime Text: Build 3142

This is third version.

**Comment by mooskagh** [comment]
I have the same issue.
